fname = input("Enter first name : ")
lname = input("Enter last name : ")
email = input("Enter email address : ")
p_number = input("Enter phone number : ")
job_title = input("Enter Job Title : ")
id_number = input("Enter ID number : ")

print()
print("---------------------------------------------")
print(f"{lname.upper()}, {fname.capitalize()}")
print(job_title.title())
print(f"ID: {id_number}")
print()
print(email.lower())
print(p_number)
print("---------------------------------------------")
